spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Pa$$w0rd
    url: jdbc:mysql://localhost/hibernate_manytomany_bidir?createDatabaseIfNotExist=TRUE&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
